### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Bonsen** [SeuTao/Kaggle_TGS2018_4th_solution#1]
Congrats! Thanks for sharing.

I have some questions:
1、How to do "Data distill (Pseudo Labeling)" and Post processing?
2、Does the model101 in "Data distill (Pseudo Labeling)" means se-resnet101 or resnext101_ibna or se-resnext101_ibna?
3、Where is ibnb ？
4、How to ensemble 10 folds of single model? Average? Choose best? (It seems just voting across all cycles of each fold and then choose best fold of 10 folds?)
5、 Based 4， if u choose best fold of single model and then average different models?

Thanks.

**Comment by SeuTao** [comment]
Hi, Bonsen
1. The data distill part is based on the result of ensemble models + jigsaw post processing. We will update this part in few days.
2. Sorry for the misunderstanding,  the model101 we use in final distilling  is  se-resnet101, but I think other 101 layer network can achieve same results.
3. Early experiment showed ibna based networks outperform the ibnb ones, we excluded them from our list. 
4. We do not select any cycle or fold, just voting across 10fold*7cycle (I think it's not the best way).

**Comment by Bonsen** [comment]
Hi, @SeuTao 

In line 437 of main.py, It seems generates 10 .csv for each fold?
