### ISSUE TITLE
model_34_try got 0.857 public LB, is that right?

### ISSUE THREAD

**Issue by ltt-gddxz** [SeuTao/Kaggle_TGS2018_4th_solution#3]
I ran the code with fold index 0 and 7 cycle, the best cycle's local LB is 0.869 and public LB is 0.857. Is that right for you?

**Comment by SeuTao** [comment]
Yes. You should try all 10 folds with 7 cycles. The ensemble result should give u 0.866+ on public LB.

**Comment by ltt-gddxz** [comment]
OK，I'll try, thank you!

**Comment by SeuTao** [comment]
For model34 , a signle fold with 7 cycle may cost 6~7h (about 66s/epoch on 1 1080ti).

**Comment by ltt-gddxz** [comment]
Thank you!
