### ISSUE TITLE
单模型 运行报错

### ISSUE THREAD

**Issue by Hello-Felix** [SeuTao/Kaggle_TGS2018_4th_solution#4]
你好，我最近在精读你们的代码，我在运行单模型训练时“CUDA_VISIBLE_DEVICES=0 python train.py --mode=train --model=model_34 --model_name=model_34 --train_fold_index=0”，代码报错不存在 0.8935_for_pseudo_label.csv，pandas无法读取，请问这个文件是数据蒸馏生成的测试集伪标签数据的图片名吗，项目文件里没有。

**Comment by SeuTao** [comment]
是的，不好意思我已经修改了。参数需要设置成None，模型集成后得到的csv传入这个参数来进行伪标签的训练。
